export const UPDATE_LAST_CREATED_JOB_ID = 'UPDATE_LAST_CREATED_JOB_ID';
export const UPDATE_AIRCRAFT_LIST = 'UPDATE_AIRCRAFT_LIST';
export const UPDATE_SPECIALIST_LIST = 'UPDATE_SPECIALIST_LIST';
export const UPDATE_DISCREPANCY_LIST = 'UPDATE_DISCREPANCY_LIST';
export const INITIALIZE_SHIFTS = 'INITIALIZE_SHIFTS';
export const INITIALIZE_USER = 'INITIALIZE_USER';
export const USER_LOGOUT = 'USER_LOGOUT';

export const GET_AIRCRAFT_LIST = 'GET_AIRCRAFT_LIST';
export const GET_AIRCRAFT_LIST_SUCCESS = 'GET_AIRCRAFT_LIST_SUCCESS';
export const GET_AIRCRAFT_LIST_FAILURE = 'GET_AIRCRAFT_LIST_FAILURE';

export const GET_SPECIALIST_LIST = 'GET_SPECIALIST_LIST';
export const GET_SPECIALIST_LIST_SUCCESS = 'GET_SPECIALIST_LIST_SUCCESS';
export const GET_SPECIALIST_LIST_FAILURE = 'GET_SPECIALIST_LIST_FAILURE';

export const GET_DISCREPANCY_LIST = 'GET_DISCREPANCY_LIST';
export const GET_DISCREPANCY_LIST_SUCCESS = 'GET_DISCREPANCY_LIST_SUCCESS';
export const GET_DISCREPANCY_LIST_FAILURE = 'GET_DISCREPANCY_LIST_FAILURE';

export const GET_AUTHENTICATED_USER = 'GET_AUTHENTICATED_USER';
export const GET_AUTHENTICATED_USER_SUCCESS = 'GET_AUTHENTICATED_USER_SUCCESS';
export const GET_AUTHENTICATED_USER_FAILURE = 'GET_AUTHENTICATED_USER_FAILURE';

export const ADD_LOG = 'ADD_LOG';
export const ADD_LOGBOOK_ITEM_SUCCESS = 'ADD_LOG_SUCCESS';
export const ADD_LOGBOOK_ITEM_FAILURE = 'ADD_LOG_FAILURE';
export const ADD_LOGBOOK_OFFLINE = 'ADD_LOGBOOK_OFFLINE';
export const ADD_LOGBOOK_ITEM_OFFLINE_SUCCESS = 'ADD_LOGBOOK_ITEM_OFFLINE_SUCCESS';

export const GET_LOG = 'GET_LOG';
export const GET_LOGBOOK_ITEM_SUCCESS = 'GET_LOG_SUCCESS';
export const GET_LOGBOOK_ITEM_FAILURE = 'GET_LOG_FAILURE';

export const ADD_FEEDBACK = 'ADD_FEEDBACK';
export const ADD_FEEDBACK_SUCCESS = 'ADD_FEEDBACK_SUCCESS';
export const ADD_FEEDBACK_FAILURE = 'ADD_FEEDBACK_FAILURE';
export const ADD_FEEDBACK_OFFLINE = 'ADD_FEEDBACK_OFFLINE';

export const CREATE_JOB = 'CREATE_JOB';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_FAILURE = 'CREATE_JOB_FAILURE';
export const CREATE_JOB_OFFLINE = 'CREATE_JOB_OFFLINE';
export const CREATE_JOB_OFFLINE_SUCCESS = 'CREATE_JOB_OFFLINE_SUCCESS';
export const CREATE_JOB_OFFLINE_FAILURE = 'CREATE_JOB_OFFLINE_FAILURE';

export const EDIT_JOB = 'EDIT_JOB';
export const EDIT_JOB_SUCCESS = 'EDIT_JOB_SUCCESS';
export const EDIT_JOB_FAILURE = 'EDIT_JOB_FAILURE';
export const EDIT_JOB_OFFLINE = 'EDIT_JOB_OFFLINE';
export const EDIT_JOB_OFFLINE_SUCCESS = 'EDIT_JOB_OFFLINE_SUCCESS';
export const EDIT_JOB_OFFLINE_FAILURE = 'EDIT_JOB_OFFLINE_FAILURE';

/** TODO PLEASE MAKE THIS ADD_SCHEDULED_JOB, this naming convention is confusing **/
export const ADD_JOB = 'ADD_JOB_JOB';
export const ADD_JOB_SUCCESS = 'ADD_JOB_SUCCESS';
export const ADD_JOB_FAILURE = 'ADD_JOB_FAILURE';
export const ADD_JOB_OFFLINE = 'ADD_JOB_OFFLINE';
export const ADD_JOB_OFFLINE_SUCCESS = 'ADD_JOB_OFFLINE_SUCCESS';
export const ADD_JOB_OFFLINE_FAILURE = 'ADD_JOB_OFFLINE_FAILURE';

export const GET_JOBS = 'GET_JOBS';
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';
export const GET_JOBS_FAILURE = 'GET_JOBS_FAILURE';

export const GET_JOB_BY_ID = 'GET_JOB_BY_ID';
export const GET_JOB_BY_ID_SUCCESS = 'GET_JOB_BY_ID_SUCCESS';
export const GET_JOB_BY_ID_FAILURE = 'GET_JOB_BY_ID_FAILURE';
export const GET_JOB_BY_ID_OFFLINE = 'GET_JOB_BY_ID_OFFLINE';
